### ISSUE TITLE
[Task] Migrate SSH dependencies to HTTPS

### ISSUE THREAD

**Issue by shiipou** [lenra-io/client-store#81]
## What should be done 
The new CI is blocked by the dependencies that use SSH and need to have an ssh-key. I can workaround it, but I think it's better for this project to just use https instead of ssh for the dependencies. That will make the dependencies easier to manage because it won't need deploy key anymore.

That issue block the deployment to the playstore in the CI

## Technical recommandation
We need to update the ssh keys for theses sub-project before the client project :

- [x] [client → client_common](https://github.com/lenra-io/client/issues/81)
- [x] [client → lenra_ui_runner](https://github.com/lenra-io/client/issues/81)
- [x] [client → lenra_components](https://github.com/lenra-io/client/issues/81)
- [x] lenra-io/client-common#86
- [x] lenra-io/lenra_ui_runner#231
- [x] [lenra_ui_runner → client_common](https://github.com/lenra-io/client/issues/231)

## Ecological concerns
What can be done to improve the ecological impact of this task ?
- Can we minimize the data send to the network ? 
- Are data stored ? Can we minimize the amount of stored data ?
- Is it CPU-intensive ? Can we reduce the CPU charge ?
- Is it RAM-intensive ? Can we reduce the RAM load ?
